spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_project?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mail:
    host: smtp.qq.com           # QQ邮箱的SMTP服务器
    port: 587                    # 端口
    username: 2197902558@qq.com   # 发件邮箱
    password: wncjkjcdceyldhic          # 不是QQ密码！是邮箱设置里生成的授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# MyBatis SQL 日志 — 会在控制台打印 SQL 语句和参数
logging:
  level:
    com.shankong.mapper: DEBUG

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:com/shankong/mapper/*.xml  # 扫描 XML 映射文件
  global-config:
    db-config:
      id-type: ASSIGN_ID  # 雪花算法自动生成 Long 型 ID

